# Generated by Django 5.2.2 on 2025-06-15 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar', models.CharField(choices=[('parts_of_speech', '品詞識別'), ('passive_voice', '受動態'), ('comparison', '比較表現')], max_length=50, verbose_name='文法項目')),
                ('question', models.TextField(verbose_name='問題文')),
                ('choice_a', models.CharField(max_length=200, verbose_name='選択肢A')),
                ('choice_b', models.CharField(max_length=200, verbose_name='選択肢B')),
                ('choice_c', models.CharField(max_length=200, verbose_name='選択肢C')),
                ('choice_d', models.CharField(max_length=200, verbose_name='選択肢D')),
                ('correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正解')),
                ('explanation', models.TextField(blank=True, verbose_name='解説')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文法問題',
                'verbose_name_plural': '文法問題',
                'ordering': ['grammar', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='問題文')),
                ('choice_a', models.CharField(max_length=200, verbose_name='選択肢A')),
                ('choice_b', models.CharField(max_length=200, verbose_name='選択肢B')),
                ('choice_c', models.CharField(max_length=200, verbose_name='選択肢C')),
                ('correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='正解')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='listening_audio/', verbose_name='音声ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'リスニング問題',
                'verbose_name_plural': 'リスニング問題',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='単語')),
                ('part_of_speech', models.CharField(max_length=20, verbose_name='品詞')),
                ('meaning_jp', models.TextField(verbose_name='日本語意味')),
                ('example', models.TextField(verbose_name='例文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TOEIC単語',
                'verbose_name_plural': 'TOEIC単語',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('vocabulary', '単語'), ('grammar', '文法'), ('listening', 'リスニング')], max_length=20, verbose_name='クイズタイプ')),
                ('question_id', models.PositiveIntegerField(verbose_name='問題ID')),
                ('user_answer', models.CharField(max_length=1, verbose_name='ユーザーの回答')),
                ('is_correct', models.BooleanField(verbose_name='正解フラグ')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='回答日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'クイズ結果',
                'verbose_name_plural': 'クイズ結果',
                'ordering': ['-answered_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('vocabulary_target', models.PositiveIntegerField(default=5, verbose_name='単語目標数')),
                ('grammar_target', models.PositiveIntegerField(default=3, verbose_name='文法目標数')),
                ('listening_target', models.PositiveIntegerField(default=1, verbose_name='リスニング目標数')),
                ('vocabulary_completed', models.PositiveIntegerField(default=0, verbose_name='単語完了数')),
                ('grammar_completed', models.PositiveIntegerField(default=0, verbose_name='文法完了数')),
                ('listening_completed', models.PositiveIntegerField(default=0, verbose_name='リスニング完了数')),
                ('is_completed', models.BooleanField(default=False, verbose_name='ミッション完了フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '日次ミッション',
                'verbose_name_plural': '日次ミッション',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_day', models.PositiveIntegerField(default=1, verbose_name='学習日数')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='総合スコア')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammar_completed', models.ManyToManyField(blank=True, to='quiz.grammarquestion', verbose_name='完了した文法問題')),
                ('listening_completed', models.ManyToManyField(blank=True, to='quiz.listeningquestion', verbose_name='完了したリスニング問題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('vocabulary_completed', models.ManyToManyField(blank=True, to='quiz.vocabulary', verbose_name='完了した単語')),
            ],
            options={
                'verbose_name': 'ユーザー進捗',
                'verbose_name_plural': 'ユーザー進捗',
                'unique_together': {('user',)},
            },
        ),
    ]
