# Generated by Django 5.2.2 on 2025-06-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_grammarquestion_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='解説'),
        ),
    ]
