# Generated by Django 5.2.1 on 2025-06-07 15:22

import ckeditor_uploader.fields
import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_rich',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='本文（リッチエディタ）'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='本文（Markdown）'),
        ),
    ]
