# Generated by Django 5.2.2 on 2025-06-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='description',
            field=models.TextField(blank=True, help_text='カテゴリの説明（任意）', verbose_name='説明'),
        ),
    ]
